"""
app/models/response_models.py
------------------------------
Pydantic response models for API endpoints.
Ensures consistent JSON structure and Swagger UI schema documentation.
"""

from pydantic import BaseModel, Field


class DocumentResult(BaseModel):
    """A single chunk result from FAISS vector search. Used in both SearchResponse and ChatResponse."""

    chunk_id: int   = Field(description="Chunk index in the vector store")
    text: str       = Field(description="Chunk text content")
    topic: str      = Field(description="Topic category (e.g. History, Tourism, Food)")
    source: str     = Field(description="Source file path")
    score: float    = Field(description="Similarity score from FAISS inner-product search")

    model_config = {
        "json_schema_extra": {
            "examples": [{
                "chunk_id": 12,
                "text": "Bánh khọt là món ăn đặc sản nổi tiếng nhất của Vũng Tàu...",
                "topic": "Ẩm thực",
                "source": "knowledge/food.txt",
                "score": 0.8712,
            }]
        }
    }


class SearchResponse(BaseModel):
    """Response for GET /search."""

    query: str                    = Field(description="Original search query")
    total: int                    = Field(description="Number of results returned")
    results: list[DocumentResult] = Field(description="Chunks ordered by descending score")


class ChatResponse(BaseModel):
    """Response for POST /chat."""

    question: str                 = Field(description="Original user question")
    answer: str                   = Field(description="Answer generated by Arcee-VyLinh")
    sources: list[DocumentResult] = Field(description="Chunks used to build the context")

    model_config = {
        "json_schema_extra": {
            "examples": [{
                "question": "Vũng Tàu có những bãi biển nào nổi tiếng?",
                "answer": "Vũng Tàu có nhiều bãi biển đẹp như Bãi Sau, Bãi Trước, Bãi Dâu...",
                "sources": [{
                    "chunk_id": 5,
                    "text": "Bãi Sau là bãi biển lớn nhất và nổi tiếng nhất...",
                    "topic": "Bãi biển",
                    "source": "knowledge/beaches.txt",
                    "score": 0.9123,
                }],
            }]
        }
    }


class HealthResponse(BaseModel):
    """Response for GET /health."""

    status: str              = Field(description="'ok' when server is running normally")
    vector_store_loaded: bool = Field(description="True if FAISS index is loaded")
    llm_loaded: bool         = Field(description="True if LLM model is loaded")
    num_chunks: int          = Field(description="Total chunks in the vector store")
    app_name: str
    version: str
